// ==============================|| EXPORT DOCUMENTS API SERVICE ||============================== //

import { BaseService } from 'services/http';
import type { ApiResult, PaginationResult, QueryRequest } from 'services/http/types';

import type { ExportDocument, ExportDocumentFormData } from '../types';

// ==================== REQUEST TYPES ====================

export interface CreateExportDocumentRequest extends Omit<ExportDocumentFormData, 'documentNo'> {
  // documentNo will be auto-generated by server
}

export interface UpdateExportDocumentRequest extends ExportDocumentFormData {}

// ==================== SERVICE CLASS ====================

/**
 * Export Document Service Class
 * Extends BaseService to inherit all HTTP methods
 */
class ExportDocumentService extends BaseService {
  /**
   * Get paginated list of export documents
   *
   * @param params - Query parameters (page, size, search, sort)
   * @returns Paginated result
   */
  async getExportDocuments(params?: QueryRequest): Promise<ApiResult<PaginationResult<ExportDocument>>> {
    return this.get<PaginationResult<ExportDocument>>('/api/export-documents', params);
  }

  /**
   * Get a single export document by ID
   *
   * @param id - Export document ID
   * @returns Single export document result
   */
  async getExportDocumentById(id: string): Promise<ApiResult<ExportDocument>> {
    return this.get<ExportDocument>(`/api/export-documents/${id}`);
  }

  /**
   * Create a new export document
   *
   * @param payload - Export document data
   * @returns Created export document result
   */
  async createExportDocument(payload: CreateExportDocumentRequest): Promise<ApiResult<ExportDocument>> {
    return this.post<CreateExportDocumentRequest, ExportDocument>('/api/export-documents', payload);
  }

  /**
   * Update an existing export document
   *
   * @param id - Export document ID
   * @param payload - Updated data
   * @returns Updated export document result
   */
  async updateExportDocument(id: string, payload: UpdateExportDocumentRequest): Promise<ApiResult<ExportDocument>> {
    return this.put<UpdateExportDocumentRequest, ExportDocument>(`/api/export-documents/${id}`, payload);
  }

  /**
   * Delete an export document
   *
   * @param id - Export document ID
   * @returns Delete operation result
   */
  async deleteExportDocument(id: string): Promise<ApiResult<void>> {
    return this.delete<void>(`/api/export-documents/${id}`);
  }

  /**
   * Bulk delete export documents
   *
   * @param ids - Array of export document IDs
   * @returns Delete operation result
   */
  async bulkDeleteExportDocuments(ids: string[]): Promise<ApiResult<void>> {
    return this.delete<void>('/api/export-documents/bulk', undefined, { ids });
  }

  /**
   * Issue document (change status from draft to issued)
   *
   * @param id - Export document ID
   * @returns Updated export document result
   */
  async issueDocument(id: string): Promise<ApiResult<ExportDocument>> {
    return this.post<{ status: 'issued' }, ExportDocument>(`/api/export-documents/${id}/issue`, { status: 'issued' });
  }

  /**
   * Export document to PDF
   *
   * @param id - Export document ID
   * @returns PDF file
   */
  async exportToPDF(id: string): Promise<ApiResult<Blob>> {
    return this.getDownload(`/api/export-documents/${id}/pdf`);
  }
}

// ==================== EXPORT SINGLETON ====================

const exportDocumentService = new ExportDocumentService();
export default exportDocumentService;
