import { SaveOutlined, CloseOutlined } from '@ant-design/icons';
import { Stack, Button } from '@mui/material';
import Grid from '@mui/material/Grid';
import { Formik, Form } from 'formik';
import { useCallback } from 'react';
import { useNavigate } from 'react-router-dom';

// project imports
import MainCard from 'components/MainCard';

import CustomerForm from '../components/CustomerForm';
import { CUSTOMER_URLS } from '../types/constants';
import type { CustomerFormData } from '../types/form';
import { customerSchema, customerDefaultValues } from '../validation';

// ==============================|| CUSTOMER CREATE PAGE ||============================== //

const CustomerCreatePage = () => {
  const navigate = useNavigate();

  // Initial form values
  const initialValues: CustomerFormData = {
    ...customerDefaultValues,
    code: 'KH-XXXX' // Placeholder - will be generated by server
  };

  // Handle form submission (mock)
  const handleSubmit = useCallback(
    async (values: CustomerFormData) => {
      // Mock API call - simulate network delay
      console.warn('Creating customer:', values);
      await new Promise((resolve) => setTimeout(resolve, 1000));

      // Mock: Generate a new ID and navigate to detail page
      const mockNewId = `mock-${Date.now()}`;
      alert('Tạo khách hàng thành công! (Mock)');
      navigate(CUSTOMER_URLS.DETAIL(mockNewId));
    },
    [navigate]
  );

  // Handle cancel
  const handleCancel = useCallback(() => {
    navigate(CUSTOMER_URLS.LIST);
  }, [navigate]);

  return (
    <Formik initialValues={initialValues} validationSchema={customerSchema} onSubmit={handleSubmit} validateOnChange validateOnBlur>
      {({ isSubmitting, dirty }) => (
        <Form>
          <MainCard
            title="Tạo khách hàng mới"
            secondary={
              <Stack direction="row" spacing={1}>
                <Button variant="outlined" color="secondary" startIcon={<CloseOutlined />} onClick={handleCancel} disabled={isSubmitting}>
                  Hủy
                </Button>
                <Button type="submit" variant="contained" color="primary" startIcon={<SaveOutlined />} disabled={isSubmitting || !dirty}>
                  {isSubmitting ? 'Đang lưu...' : 'Lưu hồ sơ'}
                </Button>
              </Stack>
            }
          >
            <Grid container spacing={3} sx={{ p: 1 }}>
              <Grid size={12}>
                <CustomerForm mode="create" />
              </Grid>
            </Grid>
          </MainCard>
        </Form>
      )}
    </Formik>
  );
};

export default CustomerCreatePage;
