import { SaveOutlined, CloseOutlined } from '@ant-design/icons';
import { Stack, Button } from '@mui/material';
import Grid from '@mui/material/Grid';
import { Formik, Form } from 'formik';
import { useCallback } from 'react';
import { useNavigate } from 'react-router-dom';

// project imports
import MainCard from 'components/MainCard';

import ExportOrderForm from '../components/ExportOrderForm';
import { EXPORT_ORDER_URLS } from '../types/constants';
import type { ExportOrderFormData } from '../types/form';
import { exportOrderSchema, exportOrderDefaultValues } from '../validation';

// ==============================|| EXPORT ORDER CREATE PAGE ||============================== //

const ExportOrderCreatePage = () => {
  const navigate = useNavigate();

  // Initial form values
  const initialValues: ExportOrderFormData = {
    ...exportOrderDefaultValues,
    orderNo: 'XK-XXXX' // Placeholder - will be generated by server
  };

  // Handle form submission (mock)
  const handleSubmit = useCallback(
    async (values: ExportOrderFormData) => {
      // Mock API call - simulate network delay
      console.warn('Creating export order:', values);
      await new Promise((resolve) => setTimeout(resolve, 1000));

      // Mock: Generate a new ID and navigate to detail page
      const mockNewId = `mock-${Date.now()}`;
      alert('Tạo đơn hàng xuất khẩu thành công! (Mock)');
      navigate(EXPORT_ORDER_URLS.DETAIL(mockNewId));
    },
    [navigate]
  );

  // Handle cancel
  const handleCancel = useCallback(() => {
    navigate(EXPORT_ORDER_URLS.LIST);
  }, [navigate]);

  return (
    <Formik initialValues={initialValues} validationSchema={exportOrderSchema} onSubmit={handleSubmit} validateOnChange validateOnBlur>
      {({ isSubmitting, dirty }) => (
        <Form>
          <MainCard
            title="Tạo đơn hàng xuất khẩu mới"
            secondary={
              <Stack direction="row" spacing={1}>
                <Button variant="outlined" color="secondary" startIcon={<CloseOutlined />} onClick={handleCancel} disabled={isSubmitting}>
                  Hủy
                </Button>
                <Button type="submit" variant="contained" color="primary" startIcon={<SaveOutlined />} disabled={isSubmitting || !dirty}>
                  {isSubmitting ? 'Đang lưu...' : 'Lưu'}
                </Button>
              </Stack>
            }
          >
            <Grid container spacing={3} sx={{ p: 1 }}>
              <Grid size={12}>
                <ExportOrderForm mode="create" />
              </Grid>
            </Grid>
          </MainCard>
        </Form>
      )}
    </Formik>
  );
};

export default ExportOrderCreatePage;
