// ==============================|| PARTNERS API SERVICE ||============================== //

import { BaseService } from 'services/http';
import type { ApiResult, PaginationResult, QueryRequest } from 'services/http/types';

import type { Partner, PartnerFormData } from '../types';

// ==================== REQUEST TYPES ====================

export interface CreatePartnerRequest extends Omit<PartnerFormData, 'code'> {
  // code will be auto-generated by server
}

export interface UpdatePartnerRequest extends PartnerFormData {}

// ==================== SERVICE CLASS ====================

/**
 * Partner Service Class
 * Extends BaseService to inherit all HTTP methods
 */
class PartnerService extends BaseService {
  /**
   * Get paginated list of partners
   *
   * @param params - Query parameters (page, size, search, sort)
   * @returns Paginated result
   */
  async getPartners(params?: QueryRequest): Promise<ApiResult<PaginationResult<Partner>>> {
    return this.get<PaginationResult<Partner>>('/api/partners', params);
  }

  /**
   * Get a single partner by ID
   *
   * @param id - Partner ID
   * @returns Single partner result
   */
  async getPartnerById(id: string): Promise<ApiResult<Partner>> {
    return this.get<Partner>(`/api/partners/${id}`);
  }

  /**
   * Create a new partner
   *
   * @param payload - Partner data
   * @returns Created partner result
   */
  async createPartner(payload: CreatePartnerRequest): Promise<ApiResult<Partner>> {
    return this.post<CreatePartnerRequest, Partner>('/api/partners', payload);
  }

  /**
   * Update an existing partner
   *
   * @param id - Partner ID
   * @param payload - Updated data
   * @returns Updated partner result
   */
  async updatePartner(id: string, payload: UpdatePartnerRequest): Promise<ApiResult<Partner>> {
    return this.put<UpdatePartnerRequest, Partner>(`/api/partners/${id}`, payload);
  }

  /**
   * Delete a partner
   *
   * @param id - Partner ID
   * @returns Delete operation result
   */
  async deletePartner(id: string): Promise<ApiResult<void>> {
    return this.delete<void>(`/api/partners/${id}`);
  }

  /**
   * Bulk delete partners
   *
   * @param ids - Array of partner IDs
   * @returns Delete operation result
   */
  async bulkDeletePartners(ids: string[]): Promise<ApiResult<void>> {
    return this.delete<void>('/api/partners/bulk', undefined, { ids });
  }
}

// ==================== EXPORT SINGLETON ====================

const partnerService = new PartnerService();
export default partnerService;
