import { SaveOutlined, CloseOutlined } from '@ant-design/icons';
import { Stack, Button } from '@mui/material';
import Grid from '@mui/material/Grid';
import { Formik, Form } from 'formik';
import { useCallback } from 'react';
import { useNavigate } from 'react-router-dom';

// project imports
import MainCard from 'components/MainCard';

import ExportDocumentForm from '../components/ExportDocumentForm';
import { EXPORT_DOCUMENT_URLS } from '../types/constants';
import type { ExportDocumentFormData } from '../types/form';
import { exportDocumentSchema, exportDocumentDefaultValues } from '../validation';

// ==============================|| EXPORT DOCUMENT CREATE PAGE ||============================== //

const ExportDocumentCreatePage = () => {
  const navigate = useNavigate();

  // Initial form values
  const initialValues: ExportDocumentFormData = {
    ...exportDocumentDefaultValues,
    documentNo: 'DOC-XXXX' // Placeholder - will be generated by server
  };

  // Handle form submission (mock)
  const handleSubmit = useCallback(
    async (values: ExportDocumentFormData) => {
      // Mock API call - simulate network delay
      console.warn('Creating export document:', values);
      await new Promise((resolve) => setTimeout(resolve, 1000));

      // Mock: Generate a new ID and navigate to detail page
      const mockNewId = `mock-${Date.now()}`;
      alert('Tạo chứng từ thành công! (Mock)');
      navigate(EXPORT_DOCUMENT_URLS.DETAIL(mockNewId));
    },
    [navigate]
  );

  // Handle cancel
  const handleCancel = useCallback(() => {
    navigate(EXPORT_DOCUMENT_URLS.LIST);
  }, [navigate]);

  return (
    <Formik initialValues={initialValues} validationSchema={exportDocumentSchema} onSubmit={handleSubmit} validateOnChange validateOnBlur>
      {({ isSubmitting, dirty }) => (
        <Form>
          <MainCard
            title="Tạo chứng từ mới"
            secondary={
              <Stack direction="row" spacing={1}>
                <Button variant="outlined" color="secondary" startIcon={<CloseOutlined />} onClick={handleCancel} disabled={isSubmitting}>
                  Quay lại
                </Button>
                <Button type="submit" variant="contained" color="primary" startIcon={<SaveOutlined />} disabled={isSubmitting || !dirty}>
                  {isSubmitting ? 'Đang lưu...' : 'Lưu chứng từ'}
                </Button>
              </Stack>
            }
          >
            <Grid container spacing={3} sx={{ p: 1 }}>
              <Grid size={12}>
                <ExportDocumentForm mode="create" />
              </Grid>
            </Grid>
          </MainCard>
        </Form>
      )}
    </Formik>
  );
};

export default ExportDocumentCreatePage;
