import { SaveOutlined, CloseOutlined } from '@ant-design/icons';
import { Stack, Button } from '@mui/material';
import Grid from '@mui/material/Grid';
import { Formik, Form } from 'formik';
import { useCallback } from 'react';
import { useNavigate } from 'react-router-dom';

// project imports
import MainCard from 'components/MainCard';

import InventoryReceiptForm from '../components/InventoryReceiptForm';
import type { InventoryReceiptFormData } from '../types';
import { INVENTORY_RECEIPT_URLS } from '../types/constants';
import { inventoryReceiptDefaultValues, inventoryReceiptSchema } from '../validation';

// ==============================|| INVENTORY RECEIPT CREATE PAGE ||============================== //

const InventoryReceiptCreatePage = () => {
  const navigate = useNavigate();

  // Initial form values
  const initialValues: InventoryReceiptFormData = {
    ...inventoryReceiptDefaultValues,
    code: 'PN-XXXX' // Placeholder - will be generated by server
  };

  // Handle form submission (mock)
  const handleSubmit = useCallback(
    async (values: InventoryReceiptFormData) => {
      // Mock API call - simulate network delay
      console.warn('Creating inventory receipt:', values);
      await new Promise((resolve) => setTimeout(resolve, 1000));

      // Mock: Generate a new ID and navigate to detail page
      const mockNewId = `mock-${Date.now()}`;
      alert('Tạo phiếu nhập kho thành công! (Mock)');
      navigate(INVENTORY_RECEIPT_URLS.DETAIL(mockNewId));
    },
    [navigate]
  );

  // Handle cancel
  const handleCancel = useCallback(() => {
    navigate(INVENTORY_RECEIPT_URLS.LIST);
  }, [navigate]);

  return (
    <Formik initialValues={initialValues} validationSchema={inventoryReceiptSchema} onSubmit={handleSubmit} validateOnChange validateOnBlur>
      {({ isSubmitting, dirty }) => (
        <Form>
          <MainCard
            title="Tạo phiếu nhập kho mới"
            secondary={
              <Stack direction="row" spacing={1}>
                <Button variant="outlined" color="secondary" startIcon={<CloseOutlined />} onClick={handleCancel} disabled={isSubmitting}>
                  Quay lại
                </Button>
                <Button type="submit" variant="contained" color="primary" startIcon={<SaveOutlined />} disabled={isSubmitting || !dirty}>
                  {isSubmitting ? 'Đang lưu...' : 'Lưu phiếu'}
                </Button>
              </Stack>
            }
          >
            <Grid container spacing={3} sx={{ p: 1 }}>
              <Grid size={12}>
                <InventoryReceiptForm mode="create" />
              </Grid>
            </Grid>
          </MainCard>
        </Form>
      )}
    </Formik>
  );
};

export default InventoryReceiptCreatePage;
