import { SaveOutlined, CloseOutlined } from '@ant-design/icons';
import { Stack, Button } from '@mui/material';
import Grid from '@mui/material/Grid';
import { Formik, Form } from 'formik';
import { useCallback } from 'react';
import { useNavigate } from 'react-router-dom';

// project imports
import MainCard from 'components/MainCard';

import WeighTicketForm from '../components/WeighTicketForm';
import type { WeighTicketFormData } from '../types';
import { WEIGH_TICKET_URLS } from '../types/constants';
import { weighTicketSchema, weighTicketDefaultValues } from '../validation';

// ==============================|| WEIGH TICKET CREATE PAGE ||============================== //

const WeighTicketCreatePage = () => {
  const navigate = useNavigate();

  // Initial form values
  const initialValues: WeighTicketFormData = {
    ...weighTicketDefaultValues,
    code: 'WT-XXXX' // Placeholder - will be generated by server
  };

  // Handle form submission (mock)
  const handleSubmit = useCallback(
    async (values: WeighTicketFormData) => {
      // Mock API call - simulate network delay
      console.warn('Creating weigh ticket:', values);
      await new Promise((resolve) => setTimeout(resolve, 1000));

      // Mock: Generate a new ID and navigate to detail page
      const mockNewId = `mock-${Date.now()}`;
      alert('Tạo phiếu cân thành công! (Mock)');
      navigate(WEIGH_TICKET_URLS.DETAIL(mockNewId));
    },
    [navigate]
  );

  // Handle cancel
  const handleCancel = useCallback(() => {
    navigate(WEIGH_TICKET_URLS.LIST);
  }, [navigate]);

  return (
    <Formik initialValues={initialValues} validationSchema={weighTicketSchema} onSubmit={handleSubmit} validateOnChange validateOnBlur>
      {({ isSubmitting, dirty }) => (
        <Form>
          <MainCard
            title="Tạo phiếu cân mới"
            secondary={
              <Stack direction="row" spacing={1}>
                <Button variant="outlined" color="secondary" startIcon={<CloseOutlined />} onClick={handleCancel} disabled={isSubmitting}>
                  Quay lại
                </Button>
                <Button type="submit" variant="contained" color="primary" startIcon={<SaveOutlined />} disabled={isSubmitting || !dirty}>
                  {isSubmitting ? 'Đang lưu...' : 'Lưu'}
                </Button>
              </Stack>
            }
          >
            <Grid container spacing={3} sx={{ p: 1 }}>
              <Grid size={12}>
                <WeighTicketForm mode="create" />
              </Grid>
            </Grid>
          </MainCard>
        </Form>
      )}
    </Formik>
  );
};

export default WeighTicketCreatePage;
