// ==============================|| TRANSFERS API SERVICE ||============================== //

import { BaseService } from 'services/http';
import type { ApiResult, PaginationResult, QueryRequest } from 'services/http/types';

import type { Transfer, TransferFormData } from '../types';

// ==================== REQUEST TYPES ====================

export interface CreateTransferRequest extends Omit<TransferFormData, 'code'> {
  // code will be auto-generated by server
}

export interface UpdateTransferRequest extends TransferFormData {}

// ==================== SERVICE CLASS ====================

/**
 * Transfer Service Class
 * Extends BaseService to inherit all HTTP methods
 */
class TransferService extends BaseService {
  /**
   * Get paginated list of transfers
   *
   * @param params - Query parameters (page, size, search, sort)
   * @returns Paginated result
   */
  async getTransfers(params?: QueryRequest): Promise<ApiResult<PaginationResult<Transfer>>> {
    return this.get<PaginationResult<Transfer>>('/api/transfers', params);
  }

  /**
   * Get a single transfer by ID
   *
   * @param id - Transfer ID
   * @returns Single transfer result
   */
  async getTransferById(id: string): Promise<ApiResult<Transfer>> {
    return this.get<Transfer>(`/api/transfers/${id}`);
  }

  /**
   * Create a new transfer
   *
   * @param payload - Transfer data
   * @returns Created transfer result
   */
  async createTransfer(payload: CreateTransferRequest): Promise<ApiResult<Transfer>> {
    return this.post<CreateTransferRequest, Transfer>('/api/transfers', payload);
  }

  /**
   * Update an existing transfer
   *
   * @param id - Transfer ID
   * @param payload - Updated data
   * @returns Updated transfer result
   */
  async updateTransfer(id: string, payload: UpdateTransferRequest): Promise<ApiResult<Transfer>> {
    return this.put<UpdateTransferRequest, Transfer>(`/api/transfers/${id}`, payload);
  }

  /**
   * Delete a transfer
   *
   * @param id - Transfer ID
   * @returns Delete operation result
   */
  async deleteTransfer(id: string): Promise<ApiResult<void>> {
    return this.delete<void>(`/api/transfers/${id}`);
  }

  /**
   * Bulk delete transfers
   *
   * @param ids - Array of transfer IDs
   * @returns Delete operation result
   */
  async bulkDeleteTransfers(ids: string[]): Promise<ApiResult<void>> {
    return this.delete<void>('/api/transfers/bulk', undefined, { ids });
  }

  /**
   * Confirm transfer (change status from draft to transferred)
   *
   * @param id - Transfer ID
   * @returns Updated transfer result
   */
  async confirmTransfer(id: string): Promise<ApiResult<Transfer>> {
    return this.post<Record<string, never>, Transfer>(`/api/transfers/${id}/confirm`, {});
  }

  /**
   * Export transfers to Excel
   *
   * @param params - Query parameters for filtering
   * @returns Excel file blob
   */
  async exportExcel(params?: QueryRequest): Promise<ApiResult<Blob>> {
    return this.getDownload('/api/transfers/export/excel', params);
  }

  /**
   * Export transfers to PDF
   *
   * @param params - Query parameters for filtering
   * @returns PDF file blob
   */
  async exportPDF(params?: QueryRequest): Promise<ApiResult<Blob>> {
    return this.getDownload('/api/transfers/export/pdf', params);
  }
}

// ==================== EXPORT SINGLETON ====================

const transferService = new TransferService();
export default transferService;
