import { SaveOutlined, CloseOutlined } from '@ant-design/icons';
import { Stack, Button } from '@mui/material';
import Grid from '@mui/material/Grid';
import { Formik, Form } from 'formik';
import { useCallback } from 'react';
import { useNavigate } from 'react-router-dom';

// project imports
import MainCard from 'components/MainCard';

import LogisticsCostForm from '../components/LogisticsCostForm';
import { LOGISTICS_COSTING_URLS } from '../types/constants';
import type { LogisticsCostFormData } from '../types/form';
import { logisticsCostSchema, logisticsCostDefaultValues } from '../validation';

// ==============================|| LOGISTICS COST CREATE PAGE ||============================== //

const LogisticsCostCreatePage = () => {
  const navigate = useNavigate();

  // Initial form values
  const initialValues: LogisticsCostFormData = {
    ...logisticsCostDefaultValues,
    costCode: 'CP-XXXX' // Placeholder - will be generated by server
  };

  // Handle form submission (mock)
  const handleSubmit = useCallback(
    async (values: LogisticsCostFormData) => {
      // Mock API call - simulate network delay
      console.warn('Creating logistics cost:', values);
      await new Promise((resolve) => setTimeout(resolve, 1000));

      // Mock: Generate a new ID and navigate to detail page
      const mockNewId = `mock-${Date.now()}`;
      alert('Tạo chi phí logistics thành công! (Mock)');
      navigate(LOGISTICS_COSTING_URLS.DETAIL(mockNewId));
    },
    [navigate]
  );

  // Handle cancel
  const handleCancel = useCallback(() => {
    navigate(LOGISTICS_COSTING_URLS.LIST);
  }, [navigate]);

  return (
    <Formik initialValues={initialValues} validationSchema={logisticsCostSchema} onSubmit={handleSubmit} validateOnChange validateOnBlur>
      {({ isSubmitting, dirty }) => (
        <Form>
          <MainCard
            title="Tạo chi phí logistics mới"
            secondary={
              <Stack direction="row" spacing={1}>
                <Button variant="outlined" color="secondary" startIcon={<CloseOutlined />} onClick={handleCancel} disabled={isSubmitting}>
                  Quay lại
                </Button>
                <Button type="submit" variant="contained" color="primary" startIcon={<SaveOutlined />} disabled={isSubmitting || !dirty}>
                  {isSubmitting ? 'Đang lưu...' : 'Lưu chi phí'}
                </Button>
              </Stack>
            }
          >
            <Grid container spacing={3} sx={{ p: 1 }}>
              <Grid size={12}>
                <LogisticsCostForm mode="create" />
              </Grid>
            </Grid>
          </MainCard>
        </Form>
      )}
    </Formik>
  );
};

export default LogisticsCostCreatePage;
