import { SaveOutlined, CloseOutlined } from '@ant-design/icons';
import { Stack, Button } from '@mui/material';
import Grid from '@mui/material/Grid';
import { Formik, Form } from 'formik';
import { useCallback } from 'react';
import { useNavigate } from 'react-router-dom';

// project imports
import MainCard from 'components/MainCard';

import MaterialReceiptForm from '../components/MaterialReceiptForm';
import type { MaterialReceiptFormData } from '../types';
import { MATERIAL_RECEIPT_URLS } from '../types/constants';
import { materialReceiptSchema, materialReceiptDefaultValues } from '../validation';

// ==============================|| MATERIAL RECEIPT CREATE PAGE ||============================== //

const MaterialReceiptCreatePage = () => {
  const navigate = useNavigate();

  // Initial form values
  const initialValues: MaterialReceiptFormData = {
    ...materialReceiptDefaultValues,
    code: 'PN-XXXX' // Placeholder - will be generated by server
  };

  // Handle form submission
  const handleSubmit = useCallback(
    async (values: MaterialReceiptFormData) => {
      // TODO: Call API to create material receipt
      // const response = await materialReceiptService.createMaterialReceipt(values);
      // if (response.success) {
      //   navigate(MATERIAL_RECEIPT_URLS.DETAIL(response.data.id));
      // }

      // Mock API call - simulate network delay
      console.warn('Creating material receipt:', values);
      await new Promise((resolve) => setTimeout(resolve, 1000));

      // Mock: Generate a new ID and navigate to detail page
      const mockNewId = `receipt-${Date.now()}`;
      alert('Tạo phiếu nhập kho thành công! (Mock)');
      navigate(MATERIAL_RECEIPT_URLS.DETAIL(mockNewId));
    },
    [navigate]
  );

  // Handle cancel
  const handleCancel = useCallback(() => {
    navigate(MATERIAL_RECEIPT_URLS.LIST);
  }, [navigate]);

  return (
    <Formik initialValues={initialValues} validationSchema={materialReceiptSchema} onSubmit={handleSubmit} validateOnChange validateOnBlur>
      {({ isSubmitting, dirty }) => (
        <Form>
          <MainCard
            title="Tạo phiếu nhập kho mới"
            secondary={
              <Stack direction="row" spacing={1}>
                <Button variant="outlined" color="secondary" startIcon={<CloseOutlined />} onClick={handleCancel} disabled={isSubmitting}>
                  Quay lại danh sách
                </Button>
                <Button type="submit" variant="contained" color="primary" startIcon={<SaveOutlined />} disabled={isSubmitting || !dirty}>
                  {isSubmitting ? 'Đang lưu...' : 'Lưu'}
                </Button>
              </Stack>
            }
          >
            <Grid container spacing={3} sx={{ p: 1 }}>
              <Grid size={12}>
                <MaterialReceiptForm mode="create" />
              </Grid>
            </Grid>
          </MainCard>
        </Form>
      )}
    </Formik>
  );
};

export default MaterialReceiptCreatePage;
