// ==============================|| PAYMENT ORDERS API SERVICE ||============================== //

import { BaseService } from 'services/http';
import type { ApiResult, PaginationResult, QueryRequest } from 'services/http/types';

import type { PaymentOrder, PaymentOrderFormData } from '../types';

// ==================== REQUEST TYPES ====================

export interface CreatePaymentOrderRequest extends Omit<PaymentOrderFormData, 'code' | 'attachment'> {
  // code will be auto-generated by server
  // attachment will be handled separately as file upload
}

export interface UpdatePaymentOrderRequest extends PaymentOrderFormData {}

// ==================== SERVICE CLASS ====================

/**
 * Payment Order Service Class
 * Extends BaseService to inherit all HTTP methods
 */
class PaymentOrderService extends BaseService {
  /**
   * Get paginated list of payment orders
   *
   * @param params - Query parameters (page, size, search, sort)
   * @returns Paginated result
   */
  async getPaymentOrders(params?: QueryRequest): Promise<ApiResult<PaginationResult<PaymentOrder>>> {
    return this.get<PaginationResult<PaymentOrder>>('/api/payment-orders', params);
  }

  /**
   * Get a single payment order by ID
   *
   * @param id - Payment Order ID
   * @returns Single payment order result
   */
  async getPaymentOrderById(id: string): Promise<ApiResult<PaymentOrder>> {
    return this.get<PaymentOrder>(`/api/payment-orders/${id}`);
  }

  /**
   * Create a new payment order
   *
   * @param payload - Payment order data
   * @returns Created payment order result
   */
  async createPaymentOrder(payload: CreatePaymentOrderRequest): Promise<ApiResult<PaymentOrder>> {
    return this.post<CreatePaymentOrderRequest, PaymentOrder>('/api/payment-orders', payload);
  }

  /**
   * Update an existing payment order
   *
   * @param id - Payment Order ID
   * @param payload - Updated data
   * @returns Updated payment order result
   */
  async updatePaymentOrder(id: string, payload: UpdatePaymentOrderRequest): Promise<ApiResult<PaymentOrder>> {
    return this.put<UpdatePaymentOrderRequest, PaymentOrder>(`/api/payment-orders/${id}`, payload);
  }

  /**
   * Delete a payment order
   *
   * @param id - Payment Order ID
   * @returns Delete operation result
   */
  async deletePaymentOrder(id: string): Promise<ApiResult<void>> {
    return this.delete<void>(`/api/payment-orders/${id}`);
  }

  /**
   * Bulk delete payment orders
   *
   * @param ids - Array of payment order IDs
   * @returns Delete operation result
   */
  async bulkDeletePaymentOrders(ids: string[]): Promise<ApiResult<void>> {
    return this.delete<void>('/api/payment-orders/bulk', undefined, { ids });
  }

  /**
   * Submit payment order for approval (change status from draft to pending)
   *
   * @param id - Payment Order ID
   * @returns Updated payment order result
   */
  async submitForApproval(id: string): Promise<ApiResult<PaymentOrder>> {
    return this.post<Record<string, never>, PaymentOrder>(`/api/payment-orders/${id}/submit`, {});
  }

  /**
   * Export payment orders to Excel
   *
   * @param params - Query parameters for filtering
   * @returns Excel file blob
   */
  async exportExcel(params?: QueryRequest): Promise<ApiResult<Blob>> {
    return this.getDownload('/api/payment-orders/export/excel', params);
  }

  /**
   * Export payment orders to PDF
   *
   * @param params - Query parameters for filtering
   * @returns PDF file blob
   */
  async exportPDF(params?: QueryRequest): Promise<ApiResult<Blob>> {
    return this.getDownload('/api/payment-orders/export/pdf', params);
  }

  /**
   * Print payment order
   *
   * @param id - Payment Order ID
   * @returns PDF file blob
   */
  async printPaymentOrder(id: string): Promise<ApiResult<Blob>> {
    return this.getDownload(`/api/payment-orders/${id}/print`);
  }
}

// ==================== EXPORT SINGLETON ====================

const paymentOrderService = new PaymentOrderService();
export default paymentOrderService;
