import { SaveOutlined, CloseOutlined } from '@ant-design/icons';
import { Stack, Button } from '@mui/material';
import Grid from '@mui/material/Grid';
import { Formik, Form } from 'formik';
import { useCallback } from 'react';
import { useNavigate } from 'react-router-dom';

// project imports
import MainCard from 'components/MainCard';

import PaymentOrderForm from '../components/PaymentOrderForm';
import { PAYMENT_ORDER_URLS } from '../types/constants';
import type { PaymentOrderFormData } from '../types/form';
import { paymentOrderSchema, paymentOrderDefaultValues } from '../validation';

// ==============================|| PAYMENT ORDER CREATE PAGE ||============================== //

const PaymentCreatePage = () => {
  const navigate = useNavigate();

  // Initial form values
  const initialValues: PaymentOrderFormData = {
    ...paymentOrderDefaultValues,
    code: 'PO-XXXX' // Placeholder - will be generated by server
  };

  // Handle form submission (mock)
  const handleSubmit = useCallback(
    async (values: PaymentOrderFormData) => {
      // Mock API call - simulate network delay
      console.warn('Creating payment order:', values);
      await new Promise((resolve) => setTimeout(resolve, 1000));

      // Mock: Generate a new ID and navigate to detail page
      const mockNewId = `mock-${Date.now()}`;
      alert('Tạo phiếu chi thành công! (Mock)');
      navigate(PAYMENT_ORDER_URLS.DETAIL(mockNewId));
    },
    [navigate]
  );

  // Handle cancel
  const handleCancel = useCallback(() => {
    navigate(PAYMENT_ORDER_URLS.LIST);
  }, [navigate]);

  return (
    <Formik initialValues={initialValues} validationSchema={paymentOrderSchema} onSubmit={handleSubmit} validateOnChange validateOnBlur>
      {({ isSubmitting, dirty }) => (
        <Form>
          <MainCard
            title="Tạo phiếu chi mới"
            secondary={
              <Stack direction="row" spacing={1}>
                <Button variant="outlined" color="secondary" startIcon={<CloseOutlined />} onClick={handleCancel} disabled={isSubmitting}>
                  Quay lại
                </Button>
                <Button type="submit" variant="contained" color="primary" startIcon={<SaveOutlined />} disabled={isSubmitting || !dirty}>
                  {isSubmitting ? 'Đang lưu...' : 'Lưu PO'}
                </Button>
              </Stack>
            }
          >
            <Grid container spacing={3} sx={{ p: 1 }}>
              <Grid size={12}>
                <PaymentOrderForm mode="create" />
              </Grid>
            </Grid>
          </MainCard>
        </Form>
      )}
    </Formik>
  );
};

export default PaymentCreatePage;
