// ==============================|| CUSTOMER CRM API SERVICE ||============================== //

import { BaseService } from 'services/http';
import type { ApiResult, PaginationResult, QueryRequest } from 'services/http/types';

import type { Customer, CustomerFormData } from '../types';

// ==================== REQUEST TYPES ====================

export interface CreateCustomerRequest extends Omit<CustomerFormData, 'code'> {
  // code will be auto-generated by server
}

export interface UpdateCustomerRequest extends CustomerFormData {}

// ==================== SERVICE CLASS ====================

/**
 * Customer Service Class
 * Extends BaseService to inherit all HTTP methods
 */
class CustomerService extends BaseService {
  /**
   * Get paginated list of customers
   *
   * @param params - Query parameters (page, size, search, sort)
   * @returns Paginated result
   */
  async getCustomers(params?: QueryRequest): Promise<ApiResult<PaginationResult<Customer>>> {
    return this.get<PaginationResult<Customer>>('/api/crm/customers', params);
  }

  /**
   * Get a single customer by ID
   *
   * @param id - Customer ID
   * @returns Single customer result
   */
  async getCustomerById(id: string): Promise<ApiResult<Customer>> {
    return this.get<Customer>(`/api/crm/customers/${id}`);
  }

  /**
   * Create a new customer
   *
   * @param payload - Customer data
   * @returns Created customer result
   */
  async createCustomer(payload: CreateCustomerRequest): Promise<ApiResult<Customer>> {
    return this.post<CreateCustomerRequest, Customer>('/api/crm/customers', payload);
  }

  /**
   * Update an existing customer
   *
   * @param id - Customer ID
   * @param payload - Updated data
   * @returns Updated customer result
   */
  async updateCustomer(id: string, payload: UpdateCustomerRequest): Promise<ApiResult<Customer>> {
    return this.put<UpdateCustomerRequest, Customer>(`/api/crm/customers/${id}`, payload);
  }

  /**
   * Delete a customer
   *
   * @param id - Customer ID
   * @returns Delete operation result
   */
  async deleteCustomer(id: string): Promise<ApiResult<void>> {
    return this.delete<void>(`/api/crm/customers/${id}`);
  }

  /**
   * Bulk delete customers
   *
   * @param ids - Array of customer IDs
   * @returns Delete operation result
   */
  async bulkDeleteCustomers(ids: string[]): Promise<ApiResult<void>> {
    return this.delete<void>('/api/crm/customers/bulk', undefined, { ids });
  }
}

// ==================== EXPORT SINGLETON ====================

const customerService = new CustomerService();
export default customerService;
