import { SaveOutlined, CloseOutlined } from '@ant-design/icons';
import { Stack, Button } from '@mui/material';
import Grid from '@mui/material/Grid';
import { Formik, Form } from 'formik';
import { useCallback } from 'react';
import { useNavigate } from 'react-router-dom';

// project imports
import MainCard from 'components/MainCard';

import VesselTrackingForm from '../components/VesselTrackingForm';
import { VESSEL_TRACKING_URLS } from '../types/constants';
import type { VesselTrackingFormData } from '../types/form';
import { vesselTrackingSchema, vesselTrackingDefaultValues } from '../validation';

// ==============================|| VESSEL TRACKING CREATE PAGE ||============================== //

const VesselTrackingCreatePage = () => {
  const navigate = useNavigate();

  // Initial form values
  const initialValues: VesselTrackingFormData = {
    ...vesselTrackingDefaultValues,
    shipmentNo: 'SHIP-XXXX' // Placeholder - will be generated by server
  };

  // Handle form submission (mock)
  const handleSubmit = useCallback(
    async (values: VesselTrackingFormData) => {
      // Mock API call - simulate network delay
      console.warn('Creating vessel tracking:', values);
      await new Promise((resolve) => setTimeout(resolve, 1000));

      // Mock: Generate a new ID and navigate to detail page
      const mockNewId = `mock-${Date.now()}`;
      alert('Tạo chuyến tàu thành công! (Mock)');
      navigate(VESSEL_TRACKING_URLS.DETAIL(mockNewId));
    },
    [navigate]
  );

  // Handle cancel
  const handleCancel = useCallback(() => {
    navigate(VESSEL_TRACKING_URLS.LIST);
  }, [navigate]);

  return (
    <Formik initialValues={initialValues} validationSchema={vesselTrackingSchema} onSubmit={handleSubmit} validateOnChange validateOnBlur>
      {({ isSubmitting, dirty }) => (
        <Form>
          <MainCard
            title="Tạo chuyến tàu mới"
            secondary={
              <Stack direction="row" spacing={1}>
                <Button variant="outlined" color="secondary" startIcon={<CloseOutlined />} onClick={handleCancel} disabled={isSubmitting}>
                  Quay lại
                </Button>
                <Button type="submit" variant="contained" color="primary" startIcon={<SaveOutlined />} disabled={isSubmitting || !dirty}>
                  {isSubmitting ? 'Đang lưu...' : 'Lưu'}
                </Button>
              </Stack>
            }
          >
            <Grid container spacing={3} sx={{ p: 1 }}>
              <Grid size={12}>
                <VesselTrackingForm mode="create" />
              </Grid>
            </Grid>
          </MainCard>
        </Form>
      )}
    </Formik>
  );
};

export default VesselTrackingCreatePage;
