// ==============================|| WORKFORCE DISPATCH API SERVICE ||============================== //

import BaseService from 'services/http/base-service';
import type { ApiResult, PaginationResult, QueryRequest } from 'services/http/types';

import type { WorkforceDispatchOrder, WorkforceDispatchOrderFormData } from '../types';

// ==================== REQUEST TYPES ====================

export interface CreateWorkforceDispatchOrderRequest extends Omit<WorkforceDispatchOrderFormData, 'code'> {
  // code will be auto-generated by server
}

export interface UpdateWorkforceDispatchOrderRequest extends WorkforceDispatchOrderFormData {}

// ==================== SERVICE CLASS ====================

/**
 * Workforce Dispatch Order Service Class
 * Extends BaseService to inherit all HTTP methods
 */
class WorkforceDispatchOrderService extends BaseService {
  /**
   * Get paginated list of workforce dispatch orders
   *
   * @param params - Query parameters (page, size, search, sort)
   * @returns Paginated result
   */
  async getWorkforceDispatchOrders(params?: QueryRequest): Promise<ApiResult<PaginationResult<WorkforceDispatchOrder>>> {
    return this.get<PaginationResult<WorkforceDispatchOrder>>('/api/admin/workforce-dispatch/orders', params);
  }

  /**
   * Get a single workforce dispatch order by ID
   *
   * @param id - Order ID
   * @returns Single order result
   */
  async getWorkforceDispatchOrderById(id: string): Promise<ApiResult<WorkforceDispatchOrder>> {
    return this.get<WorkforceDispatchOrder>(`/api/admin/workforce-dispatch/orders/${id}`);
  }

  /**
   * Create a new workforce dispatch order
   *
   * @param payload - Order data
   * @returns Created order result
   */
  async createWorkforceDispatchOrder(payload: CreateWorkforceDispatchOrderRequest): Promise<ApiResult<WorkforceDispatchOrder>> {
    return this.post<CreateWorkforceDispatchOrderRequest, WorkforceDispatchOrder>('/api/admin/workforce-dispatch/orders', payload);
  }

  /**
   * Update an existing workforce dispatch order
   *
   * @param id - Order ID
   * @param payload - Updated data
   * @returns Updated order result
   */
  async updateWorkforceDispatchOrder(id: string, payload: UpdateWorkforceDispatchOrderRequest): Promise<ApiResult<WorkforceDispatchOrder>> {
    return this.put<UpdateWorkforceDispatchOrderRequest, WorkforceDispatchOrder>(`/api/admin/workforce-dispatch/orders/${id}`, payload);
  }

  /**
   * Delete a workforce dispatch order
   *
   * @param id - Order ID
   * @returns Delete operation result
   */
  async deleteWorkforceDispatchOrder(id: string): Promise<ApiResult<void>> {
    return this.delete<void>(`/api/admin/workforce-dispatch/orders/${id}`);
  }

  /**
   * Bulk delete workforce dispatch orders
   *
   * @param ids - Array of order IDs
   * @returns Delete operation result
   */
  async bulkDeleteWorkforceDispatchOrders(ids: string[]): Promise<ApiResult<void>> {
    return this.delete<void>('/api/admin/workforce-dispatch/orders/bulk', undefined, { ids });
  }

  /**
   * Submit order for approval
   *
   * @param id - Order ID
   * @returns Updated order result
   */
  async submitOrder(id: string): Promise<ApiResult<WorkforceDispatchOrder>> {
    return this.post<Record<string, never>, WorkforceDispatchOrder>(`/api/admin/workforce-dispatch/orders/${id}/submit`, {});
  }

  /**
   * Approve order
   *
   * @param id - Order ID
   * @returns Updated order result
   */
  async approveOrder(id: string): Promise<ApiResult<WorkforceDispatchOrder>> {
    return this.post<Record<string, never>, WorkforceDispatchOrder>(`/api/admin/workforce-dispatch/orders/${id}/approve`, {});
  }

  /**
   * Cancel order
   *
   * @param id - Order ID
   * @returns Updated order result
   */
  async cancelOrder(id: string): Promise<ApiResult<WorkforceDispatchOrder>> {
    return this.post<Record<string, never>, WorkforceDispatchOrder>(`/api/admin/workforce-dispatch/orders/${id}/cancel`, {});
  }

  /**
   * Print order as PDF
   *
   * @param id - Order ID
   * @returns PDF file blob
   */
  async printOrder(id: string): Promise<ApiResult<Blob>> {
    return this.getDownload(`/api/admin/workforce-dispatch/orders/${id}/print`);
  }
}

// ==================== EXPORT SINGLETON ====================

const workforceDispatchOrderService = new WorkforceDispatchOrderService();
export default workforceDispatchOrderService;
