// ==============================|| PRODUCTION PLAN CREATE PAGE ||============================== //

import CloseOutlined from '@ant-design/icons/CloseOutlined';
import SaveOutlined from '@ant-design/icons/SaveOutlined';
import { Stack, Button } from '@mui/material';
import Grid from '@mui/material/Grid';
import { Formik, Form } from 'formik';
import { useCallback } from 'react';
import { useNavigate } from 'react-router-dom';

// project imports
import MainCard from 'components/MainCard';

import ProductionPlanForm from '../components/ProductionPlanForm';
import type { ProductionPlanFormData } from '../types';
import { PRODUCTION_PLAN_URLS } from '../types/constants';
import { productionPlanSchema, productionPlanDefaultValues } from '../validation';

// ==============================|| PRODUCTION PLAN CREATE PAGE ||============================== //

const ProductionPlanCreatePage = () => {
  const navigate = useNavigate();

  // Initial form values
  const initialValues: ProductionPlanFormData = {
    ...productionPlanDefaultValues,
    code: 'KH-XXXX' // Placeholder - will be generated by server
  };

  // Handle form submission
  const handleSubmit = useCallback(
    async (values: ProductionPlanFormData) => {
      // TODO: Call API to create production plan
      console.warn('Creating production plan:', values);
      await new Promise((resolve) => setTimeout(resolve, 1000));

      // Mock: Generate a new ID and navigate to detail page
      const mockNewId = `mock-${Date.now()}`;
      alert('Tạo kế hoạch/lệnh sản xuất thành công! (Mock)');
      navigate(PRODUCTION_PLAN_URLS.DETAIL(mockNewId));
    },
    [navigate]
  );

  // Handle cancel
  const handleCancel = useCallback(() => {
    navigate(PRODUCTION_PLAN_URLS.LIST);
  }, [navigate]);

  return (
    <Formik initialValues={initialValues} validationSchema={productionPlanSchema} onSubmit={handleSubmit} validateOnChange validateOnBlur>
      {({ isSubmitting, dirty }) => (
        <Form>
          <MainCard
            title="Tạo kế hoạch / lệnh sản xuất mới"
            secondary={
              <Stack direction="row" spacing={1}>
                <Button variant="outlined" color="secondary" startIcon={<CloseOutlined />} onClick={handleCancel} disabled={isSubmitting}>
                  Quay lại danh sách
                </Button>
                <Button type="submit" variant="contained" color="primary" startIcon={<SaveOutlined />} disabled={isSubmitting || !dirty}>
                  {isSubmitting ? 'Đang lưu...' : 'Lưu'}
                </Button>
              </Stack>
            }
          >
            <Grid container spacing={3} sx={{ p: 1 }}>
              <Grid size={12}>
                <ProductionPlanForm mode="create" />
              </Grid>
            </Grid>
          </MainCard>
        </Form>
      )}
    </Formik>
  );
};

export default ProductionPlanCreatePage;
