// ==============================|| CONTRACTS API SERVICE ||============================== //

import { BaseService } from 'services/http';
import type { ApiResult, PaginationResult, QueryRequest } from 'services/http/types';

import type { Contract, ContractFormData } from '../types';

// ==================== REQUEST TYPES ====================

export interface CreateContractRequest extends Omit<ContractFormData, 'code' | 'attachment'> {
  // code will be auto-generated by server
  // attachment will be handled separately as file upload
}

export interface UpdateContractRequest extends ContractFormData {}

// ==================== SERVICE CLASS ====================

/**
 * Contract Service Class
 * Extends BaseService to inherit all HTTP methods
 */
class ContractService extends BaseService {
  /**
   * Get paginated list of contracts
   *
   * @param params - Query parameters (page, size, search, sort)
   * @returns Paginated result
   */
  async getContracts(params?: QueryRequest): Promise<ApiResult<PaginationResult<Contract>>> {
    return this.get<PaginationResult<Contract>>('/api/contracts', params);
  }

  /**
   * Get a single contract by ID
   *
   * @param id - Contract ID
   * @returns Single contract result
   */
  async getContractById(id: string): Promise<ApiResult<Contract>> {
    return this.get<Contract>(`/api/contracts/${id}`);
  }

  /**
   * Create a new contract
   *
   * @param payload - Contract data
   * @returns Created contract result
   */
  async createContract(payload: CreateContractRequest): Promise<ApiResult<Contract>> {
    return this.post<CreateContractRequest, Contract>('/api/contracts', payload);
  }

  /**
   * Update an existing contract
   *
   * @param id - Contract ID
   * @param payload - Updated data
   * @returns Updated contract result
   */
  async updateContract(id: string, payload: UpdateContractRequest): Promise<ApiResult<Contract>> {
    return this.put<UpdateContractRequest, Contract>(`/api/contracts/${id}`, payload);
  }

  /**
   * Delete a contract
   *
   * @param id - Contract ID
   * @returns Delete operation result
   */
  async deleteContract(id: string): Promise<ApiResult<void>> {
    return this.delete<void>(`/api/contracts/${id}`);
  }

  /**
   * Bulk delete contracts
   *
   * @param ids - Array of contract IDs
   * @returns Delete operation result
   */
  async bulkDeleteContracts(ids: string[]): Promise<ApiResult<void>> {
    return this.delete<void>('/api/contracts/bulk', undefined, { ids });
  }

  /**
   * Activate a contract (change status from draft to active)
   *
   * @param id - Contract ID
   * @returns Updated contract result
   */
  async activateContract(id: string): Promise<ApiResult<Contract>> {
    return this.post<Record<string, never>, Contract>(`/api/contracts/${id}/activate`, {});
  }

  /**
   * Export contracts to Excel
   *
   * @param params - Query parameters for filtering
   * @returns Excel file blob
   */
  async exportExcel(params?: QueryRequest): Promise<ApiResult<Blob>> {
    return this.getDownload('/api/contracts/export/excel', params);
  }

  /**
   * Export contracts to PDF
   *
   * @param params - Query parameters for filtering
   * @returns PDF file blob
   */
  async exportPDF(params?: QueryRequest): Promise<ApiResult<Blob>> {
    return this.getDownload('/api/contracts/export/pdf', params);
  }

  /**
   * Print contract
   *
   * @param id - Contract ID
   * @returns PDF file blob
   */
  async printContract(id: string): Promise<ApiResult<Blob>> {
    return this.getDownload(`/api/contracts/${id}/print`);
  }
}

// ==================== EXPORT SINGLETON ====================

const contractService = new ContractService();
export default contractService;
