// ==============================|| TRANSFER CREATE PAGE ||============================== //

import { CloseOutlined, SaveOutlined } from '@ant-design/icons';
import { Button, Stack } from '@mui/material';
import Grid from '@mui/material/Grid';
import { Formik, Form } from 'formik';
import { useCallback } from 'react';
import { useNavigate } from 'react-router-dom';

// project imports
import MainCard from 'components/MainCard';

import transferService from '../api/index';
import TransferForm from '../components/TransferForm';
import type { TransferFormData } from '../types';
import { TRANSFER_URLS } from '../types/constants';
import { transferDefaultValues, transferSchema } from '../validation';

// ==============================|| TRANSFER CREATE PAGE ||============================== //

const TransferCreatePage = () => {
  const navigate = useNavigate();

  // Initial form values
  const initialValues: TransferFormData = {
    ...transferDefaultValues,
    code: 'TC-XXXX' // Placeholder - will be generated by server
  };

  // Handle form submission
  const handleSubmit = useCallback(
    async (values: TransferFormData) => {
      // TODO: Call API to create transfer
      console.warn('Creating transfer:', values);
      await new Promise((resolve) => setTimeout(resolve, 1000));

      // Mock: Call API
      try {
        const { code, ...createPayload } = values; // Remove code as it will be auto-generated
        const response = await transferService.createTransfer(createPayload);
        if (response.success && response.data) {
          // Navigate to detail page
          navigate(TRANSFER_URLS.DETAIL(response.data.id));
        }
      } catch (err) {
        console.error('Error creating transfer:', err);
      }
    },
    [navigate]
  );

  // Handle cancel
  const handleCancel = useCallback(() => {
    navigate(TRANSFER_URLS.LIST);
  }, [navigate]);

  return (
    <Formik initialValues={initialValues} validationSchema={transferSchema} onSubmit={handleSubmit} validateOnChange validateOnBlur>
      {({ isSubmitting, dirty, values }) => (
        <Form>
          <MainCard
            title="Tạo phiếu chuyển kho mới"
            secondary={
              <Stack direction="row" spacing={1}>
                <Button variant="outlined" color="secondary" startIcon={<CloseOutlined />} onClick={handleCancel} disabled={isSubmitting}>
                  Quay lại danh sách
                </Button>
                <Button type="submit" variant="contained" color="primary" startIcon={<SaveOutlined />} disabled={isSubmitting || !dirty}>
                  {isSubmitting ? 'Đang lưu...' : 'Lưu phiếu'}
                </Button>
              </Stack>
            }
          >
            <Grid container spacing={3} sx={{ p: 1 }}>
              <Grid size={12}>
                <TransferForm mode="create" />
              </Grid>
            </Grid>
          </MainCard>
        </Form>
      )}
    </Formik>
  );
};

export default TransferCreatePage;
