// ==============================|| QUALITY INSPECTION CREATE PAGE ||============================== //

import CloseOutlined from '@ant-design/icons/CloseOutlined';
import SaveOutlined from '@ant-design/icons/SaveOutlined';
import { Stack, Button } from '@mui/material';
import Grid from '@mui/material/Grid';
import { Formik, Form } from 'formik';
import { useCallback } from 'react';
import { useNavigate } from 'react-router-dom';

// project imports
import MainCard from 'components/MainCard';

import QualityInspectionForm from '../components/QualityInspectionForm';
import type { QualityInspectionFormData } from '../types';
import { QUALITY_URLS } from '../types/constants';
import { qualityInspectionSchema, qualityInspectionDefaultValues } from '../validation';

// ==============================|| QUALITY INSPECTION CREATE PAGE ||============================== //

const QualityInspectionCreatePage = () => {
  const navigate = useNavigate();

  // Initial form values
  const initialValues: QualityInspectionFormData = {
    ...qualityInspectionDefaultValues,
    code: 'QC-XXXX' // Placeholder - will be generated by server
  };

  // Handle form submission
  const handleSubmit = useCallback(
    async (values: QualityInspectionFormData) => {
      // TODO: Call API to create quality inspection
      console.warn('Creating quality inspection:', values);
      await new Promise((resolve) => setTimeout(resolve, 1000));

      // Mock: Generate a new ID and navigate to detail page
      const mockNewId = `mock-${Date.now()}`;
      alert('Tạo phiếu kiểm định thành công! (Mock)');
      navigate(QUALITY_URLS.DETAIL(mockNewId));
    },
    [navigate]
  );

  // Handle cancel
  const handleCancel = useCallback(() => {
    navigate(QUALITY_URLS.LIST);
  }, [navigate]);

  return (
    <Formik
      initialValues={initialValues}
      validationSchema={qualityInspectionSchema}
      onSubmit={handleSubmit}
      validateOnChange
      validateOnBlur
    >
      {({ isSubmitting, dirty }) => (
        <Form>
          <MainCard
            title="Tạo phiếu kiểm định mới"
            secondary={
              <Stack direction="row" spacing={1}>
                <Button variant="outlined" color="secondary" startIcon={<CloseOutlined />} onClick={handleCancel} disabled={isSubmitting}>
                  Quay lại danh sách
                </Button>
                <Button type="submit" variant="contained" color="primary" startIcon={<SaveOutlined />} disabled={isSubmitting || !dirty}>
                  {isSubmitting ? 'Đang lưu...' : 'Lưu'}
                </Button>
              </Stack>
            }
          >
            <Grid container spacing={3} sx={{ p: 1 }}>
              <Grid size={12}>
                <QualityInspectionForm mode="create" />
              </Grid>
            </Grid>
          </MainCard>
        </Form>
      )}
    </Formik>
  );
};

export default QualityInspectionCreatePage;
