// ==============================|| EXPORT ORDERS API SERVICE ||============================== //

import { BaseService } from 'services/http';
import type { ApiResult, PaginationResult, QueryRequest } from 'services/http/types';

import type { ExportOrder, ExportOrderFormData } from '../types';

// ==================== REQUEST TYPES ====================

export interface CreateExportOrderRequest extends Omit<ExportOrderFormData, 'orderNo'> {
  // orderNo will be auto-generated by server
}

export interface UpdateExportOrderRequest extends ExportOrderFormData {}

// ==================== SERVICE CLASS ====================

/**
 * Export Order Service Class
 * Extends BaseService to inherit all HTTP methods
 */
class ExportOrderService extends BaseService {
  /**
   * Get paginated list of export orders
   *
   * @param params - Query parameters (page, size, search, sort)
   * @returns Paginated result
   */
  async getExportOrders(params?: QueryRequest): Promise<ApiResult<PaginationResult<ExportOrder>>> {
    return this.get<PaginationResult<ExportOrder>>('/api/export-orders', params);
  }

  /**
   * Get a single export order by ID
   *
   * @param id - Export order ID
   * @returns Single export order result
   */
  async getExportOrderById(id: string): Promise<ApiResult<ExportOrder>> {
    return this.get<ExportOrder>(`/api/export-orders/${id}`);
  }

  /**
   * Create a new export order
   *
   * @param payload - Export order data
   * @returns Created export order result
   */
  async createExportOrder(payload: CreateExportOrderRequest): Promise<ApiResult<ExportOrder>> {
    return this.post<CreateExportOrderRequest, ExportOrder>('/api/export-orders', payload);
  }

  /**
   * Update an existing export order
   *
   * @param id - Export order ID
   * @param payload - Updated data
   * @returns Updated export order result
   */
  async updateExportOrder(id: string, payload: UpdateExportOrderRequest): Promise<ApiResult<ExportOrder>> {
    return this.put<UpdateExportOrderRequest, ExportOrder>(`/api/export-orders/${id}`, payload);
  }

  /**
   * Delete an export order
   *
   * @param id - Export order ID
   * @returns Delete operation result
   */
  async deleteExportOrder(id: string): Promise<ApiResult<void>> {
    return this.delete<void>(`/api/export-orders/${id}`);
  }

  /**
   * Bulk delete export orders
   *
   * @param ids - Array of export order IDs
   * @returns Delete operation result
   */
  async bulkDeleteExportOrders(ids: string[]): Promise<ApiResult<void>> {
    return this.delete<void>('/api/export-orders/bulk', undefined, { ids });
  }
}

// ==================== EXPORT SINGLETON ====================

const exportOrderService = new ExportOrderService();
export default exportOrderService;
