// ==============================|| INVENTORY RECEIPTS API SERVICE ||============================== //

import { BaseService } from 'services/http';
import type { ApiResult, PaginationResult, QueryRequest } from 'services/http/types';

import type { InventoryReceipt, InventoryReceiptFormData } from '../types';

// ==================== REQUEST TYPES ====================

export interface CreateInventoryReceiptRequest extends Omit<InventoryReceiptFormData, 'code'> {
  // code will be auto-generated by server
}

export interface UpdateInventoryReceiptRequest extends InventoryReceiptFormData {}

// ==================== SERVICE CLASS ====================

/**
 * Inventory Receipt Service Class
 * Extends BaseService to inherit all HTTP methods
 */
class InventoryReceiptService extends BaseService {
  /**
   * Get paginated list of inventory receipts
   *
   * @param params - Query parameters (page, size, search, sort)
   * @returns Paginated result
   */
  async getInventoryReceipts(params?: QueryRequest): Promise<ApiResult<PaginationResult<InventoryReceipt>>> {
    return this.get<PaginationResult<InventoryReceipt>>('/api/inventory-receipts', params);
  }

  /**
   * Get a single inventory receipt by ID
   *
   * @param id - Inventory Receipt ID
   * @returns Single inventory receipt result
   */
  async getInventoryReceiptById(id: string): Promise<ApiResult<InventoryReceipt>> {
    return this.get<InventoryReceipt>(`/api/inventory-receipts/${id}`);
  }

  /**
   * Create a new inventory receipt
   *
   * @param payload - Inventory Receipt data
   * @returns Created inventory receipt result
   */
  async createInventoryReceipt(payload: CreateInventoryReceiptRequest): Promise<ApiResult<InventoryReceipt>> {
    return this.post<CreateInventoryReceiptRequest, InventoryReceipt>('/api/inventory-receipts', payload);
  }

  /**
   * Update an existing inventory receipt
   *
   * @param id - Inventory Receipt ID
   * @param payload - Updated data
   * @returns Updated inventory receipt result
   */
  async updateInventoryReceipt(id: string, payload: UpdateInventoryReceiptRequest): Promise<ApiResult<InventoryReceipt>> {
    return this.put<UpdateInventoryReceiptRequest, InventoryReceipt>(`/api/inventory-receipts/${id}`, payload);
  }

  /**
   * Delete an inventory receipt
   *
   * @param id - Inventory Receipt ID
   * @returns Delete operation result
   */
  async deleteInventoryReceipt(id: string): Promise<ApiResult<void>> {
    return this.delete<void>(`/api/inventory-receipts/${id}`);
  }

  /**
   * Bulk delete inventory receipts
   *
   * @param ids - Array of inventory receipt IDs
   * @returns Delete operation result
   */
  async bulkDeleteInventoryReceipts(ids: string[]): Promise<ApiResult<void>> {
    return this.delete<void>('/api/inventory-receipts/bulk', undefined, { ids });
  }

  /**
   * Confirm receipt (change status from draft to received)
   *
   * @param id - Inventory Receipt ID
   * @returns Updated inventory receipt result
   */
  async confirmReceipt(id: string): Promise<ApiResult<InventoryReceipt>> {
    return this.post<Record<string, never>, InventoryReceipt>(`/api/inventory-receipts/${id}/confirm`, {});
  }

  /**
   * Export inventory receipts to Excel
   *
   * @param params - Query parameters for filtering
   * @returns Excel file blob
   */
  async exportExcel(params?: QueryRequest): Promise<ApiResult<Blob>> {
    return this.getDownload('/api/inventory-receipts/export/excel', params);
  }

  /**
   * Export inventory receipts to PDF
   *
   * @param params - Query parameters for filtering
   * @returns PDF file blob
   */
  async exportPDF(params?: QueryRequest): Promise<ApiResult<Blob>> {
    return this.getDownload('/api/inventory-receipts/export/pdf', params);
  }
}

// ==================== EXPORT SINGLETON ====================

const inventoryReceiptService = new InventoryReceiptService();
export default inventoryReceiptService;
