// ==============================|| BATCH CREATE PAGE ||============================== //

import CloseOutlined from '@ant-design/icons/CloseOutlined';
import SaveOutlined from '@ant-design/icons/SaveOutlined';
import { Stack, Button } from '@mui/material';
import Grid from '@mui/material/Grid';
import { Formik, Form } from 'formik';
import { useCallback } from 'react';
import { useNavigate } from 'react-router-dom';

// project imports
import MainCard from 'components/MainCard';

import BatchForm from '../components/BatchForm';
import type { BatchFormData } from '../types';
import { BATCH_URLS } from '../types/constants';
import { batchSchema, batchDefaultValues } from '../validation';

// ==============================|| BATCH CREATE PAGE ||============================== //

const BatchCreatePage = () => {
  const navigate = useNavigate();

  // Initial form values
  const initialValues: BatchFormData = {
    ...batchDefaultValues,
    code: 'LO-XXXX' // Placeholder - will be generated by server
  };

  // Handle form submission
  const handleSubmit = useCallback(
    async (values: BatchFormData) => {
      // TODO: Call API to create batch
      console.warn('Creating batch:', values);
      await new Promise((resolve) => setTimeout(resolve, 1000));

      // Mock: Generate a new ID and navigate to detail page
      const mockNewId = `mock-${Date.now()}`;
      alert('Tạo lô sản xuất thành công! (Mock)');
      navigate(BATCH_URLS.DETAIL(mockNewId));
    },
    [navigate]
  );

  // Handle cancel
  const handleCancel = useCallback(() => {
    navigate(BATCH_URLS.LIST);
  }, [navigate]);

  return (
    <Formik initialValues={initialValues} validationSchema={batchSchema} onSubmit={handleSubmit} validateOnChange validateOnBlur>
      {({ isSubmitting, dirty }) => (
        <Form>
          <MainCard
            title="Tạo lô sản xuất mới"
            secondary={
              <Stack direction="row" spacing={1}>
                <Button variant="outlined" color="secondary" startIcon={<CloseOutlined />} onClick={handleCancel} disabled={isSubmitting}>
                  Quay lại danh sách
                </Button>
                <Button type="submit" variant="contained" color="primary" startIcon={<SaveOutlined />} disabled={isSubmitting || !dirty}>
                  {isSubmitting ? 'Đang lưu...' : 'Lưu'}
                </Button>
              </Stack>
            }
          >
            <Grid container spacing={3} sx={{ p: 1 }}>
              <Grid size={12}>
                <BatchForm mode="create" />
              </Grid>
            </Grid>
          </MainCard>
        </Form>
      )}
    </Formik>
  );
};

export default BatchCreatePage;
