import { SaveOutlined, CloseOutlined } from '@ant-design/icons';
import { Stack, Button } from '@mui/material';
import Grid from '@mui/material/Grid';
import { Formik, Form } from 'formik';
import { useCallback } from 'react';
import { useNavigate } from 'react-router-dom';

// project imports
import MainCard from 'components/MainCard';

import HarvestPlanForm from '../components/HarvestPlanForm';
import type { HarvestPlanFormData } from '../types';
import { HARVEST_PLAN_URLS } from '../types/constants';
import { harvestPlanSchema, harvestPlanDefaultValues } from '../validation';

// ==============================|| HARVEST PLAN CREATE PAGE ||============================== //

const HarvestPlanCreatePage = () => {
  const navigate = useNavigate();

  // Initial form values
  const initialValues: HarvestPlanFormData = {
    ...harvestPlanDefaultValues,
    code: 'HP-XXXX' // Placeholder - will be generated by server
  };

  // Handle form submission (mock)
  const handleSubmit = useCallback(
    async (values: HarvestPlanFormData) => {
      // Mock API call - simulate network delay
      console.warn('Creating harvest plan:', values);
      await new Promise((resolve) => setTimeout(resolve, 1000));

      // Mock: Generate a new ID and navigate to detail page
      const mockNewId = `mock-${Date.now()}`;
      alert('Tạo vùng trồng thành công! (Mock)');
      navigate(HARVEST_PLAN_URLS.DETAIL(mockNewId));
    },
    [navigate]
  );

  // Handle cancel
  const handleCancel = useCallback(() => {
    navigate(HARVEST_PLAN_URLS.LIST);
  }, [navigate]);

  return (
    <Formik initialValues={initialValues} validationSchema={harvestPlanSchema} onSubmit={handleSubmit} validateOnChange validateOnBlur>
      {({ isSubmitting, dirty, values }) => (
        <Form>
          <MainCard
            title="Tạo vùng trồng mới"
            secondary={
              <Stack direction="row" spacing={1}>
                <Button variant="outlined" color="secondary" startIcon={<CloseOutlined />} onClick={handleCancel} disabled={isSubmitting}>
                  Hủy
                </Button>
                <Button type="submit" variant="contained" color="primary" startIcon={<SaveOutlined />} disabled={isSubmitting || !dirty}>
                  {isSubmitting ? 'Đang lưu...' : 'Lưu'}
                </Button>
              </Stack>
            }
          >
            <Grid container spacing={3} sx={{ p: 1 }}>
              <Grid size={12}>
                <HarvestPlanForm mode="create" />
              </Grid>
            </Grid>
          </MainCard>
        </Form>
      )}
    </Formik>
  );
};

export default HarvestPlanCreatePage;
