// ==============================|| VESSEL TRACKING API SERVICE ||============================== //

import { BaseService } from 'services/http';
import type { ApiResult, PaginationResult, QueryRequest } from 'services/http/types';

import type { VesselTracking } from '../types/entity';
import type { VesselTrackingFormData } from '../types/form';

// ==================== REQUEST TYPES ====================

export interface CreateVesselTrackingRequest extends Omit<VesselTrackingFormData, 'shipmentNo'> {
  // shipmentNo will be auto-generated by server
}

export interface UpdateVesselTrackingRequest extends VesselTrackingFormData {}

// ==================== SERVICE CLASS ====================

/**
 * Vessel Tracking Service Class
 * Extends BaseService to inherit all HTTP methods
 */
class VesselTrackingService extends BaseService {
  /**
   * Get paginated list of vessel trackings
   *
   * @param params - Query parameters (page, size, search, sort)
   * @returns Paginated result
   */
  async getVesselTrackings(params?: QueryRequest): Promise<ApiResult<PaginationResult<VesselTracking>>> {
    return this.get<PaginationResult<VesselTracking>>('/api/vessel-tracking', params);
  }

  /**
   * Get a single vessel tracking by ID
   *
   * @param id - Vessel tracking ID
   * @returns Single vessel tracking result
   */
  async getVesselTrackingById(id: string): Promise<ApiResult<VesselTracking>> {
    return this.get<VesselTracking>(`/api/vessel-tracking/${id}`);
  }

  /**
   * Create a new vessel tracking
   *
   * @param payload - Vessel tracking data
   * @returns Created vessel tracking result
   */
  async createVesselTracking(payload: CreateVesselTrackingRequest): Promise<ApiResult<VesselTracking>> {
    return this.post<CreateVesselTrackingRequest, VesselTracking>('/api/vessel-tracking', payload);
  }

  /**
   * Update an existing vessel tracking
   *
   * @param id - Vessel tracking ID
   * @param payload - Updated data
   * @returns Updated vessel tracking result
   */
  async updateVesselTracking(id: string, payload: UpdateVesselTrackingRequest): Promise<ApiResult<VesselTracking>> {
    return this.put<UpdateVesselTrackingRequest, VesselTracking>(`/api/vessel-tracking/${id}`, payload);
  }

  /**
   * Delete a vessel tracking
   *
   * @param id - Vessel tracking ID
   * @returns Delete operation result
   */
  async deleteVesselTracking(id: string): Promise<ApiResult<void>> {
    return this.delete<void>(`/api/vessel-tracking/${id}`);
  }

  /**
   * Bulk delete vessel trackings
   *
   * @param ids - Array of vessel tracking IDs
   * @returns Delete operation result
   */
  async bulkDeleteVesselTrackings(ids: string[]): Promise<ApiResult<void>> {
    return this.delete<void>('/api/vessel-tracking/bulk', undefined, { ids });
  }

  /**
   * Update vessel status
   *
   * @param id - Vessel tracking ID
   * @param status - New status
   * @returns Updated vessel tracking result
   */
  async updateStatus(id: string, status: 'running' | 'arrived'): Promise<ApiResult<VesselTracking>> {
    return this.post<{ status: 'running' | 'arrived' }, VesselTracking>(`/api/vessel-tracking/${id}/status`, { status });
  }

  /**
   * Refresh tracking data
   *
   * @param id - Vessel tracking ID
   * @returns Updated vessel tracking result
   */
  async refreshTracking(id: string): Promise<ApiResult<VesselTracking>> {
    return this.post<void, VesselTracking>(`/api/vessel-tracking/${id}/refresh`, undefined);
  }
}

// ==================== EXPORT SINGLETON ====================

const vesselTrackingService = new VesselTrackingService();
export default vesselTrackingService;
