// ==============================|| ADVANCES API SERVICE ||============================== //

import { BaseService } from 'services/http';
import type { ApiResult, PaginationResult, QueryRequest } from 'services/http/types';

import type { Advance, AdvanceFormData, AdvanceApprovalFormData } from '../types';

// ==================== REQUEST TYPES ====================

export interface CreateAdvanceRequest extends Omit<AdvanceFormData, 'code'> {
  // code will be auto-generated by server
}

export interface UpdateAdvanceRequest extends AdvanceFormData {}

export interface ApproveAdvanceRequest extends AdvanceApprovalFormData {}

// ==================== SERVICE CLASS ====================

/**
 * Advance Service Class
 * Extends BaseService to inherit all HTTP methods
 */
class AdvanceService extends BaseService {
  /**
   * Get paginated list of advances
   *
   * @param params - Query parameters (page, size, search, sort)
   * @returns Paginated result
   */
  async getAdvances(params?: QueryRequest): Promise<ApiResult<PaginationResult<Advance>>> {
    return this.get<PaginationResult<Advance>>('/api/advances', params);
  }

  /**
   * Get a single advance by ID
   *
   * @param id - Advance ID
   * @returns Single advance result
   */
  async getAdvanceById(id: string): Promise<ApiResult<Advance>> {
    return this.get<Advance>(`/api/advances/${id}`);
  }

  /**
   * Create a new advance
   *
   * @param payload - Advance data
   * @returns Created advance result
   */
  async createAdvance(payload: CreateAdvanceRequest): Promise<ApiResult<Advance>> {
    return this.post<CreateAdvanceRequest, Advance>('/api/advances', payload);
  }

  /**
   * Update an existing advance
   *
   * @param id - Advance ID
   * @param payload - Updated data
   * @returns Updated advance result
   */
  async updateAdvance(id: string, payload: UpdateAdvanceRequest): Promise<ApiResult<Advance>> {
    return this.put<UpdateAdvanceRequest, Advance>(`/api/advances/${id}`, payload);
  }

  /**
   * Delete an advance
   *
   * @param id - Advance ID
   * @returns Delete operation result
   */
  async deleteAdvance(id: string): Promise<ApiResult<void>> {
    return this.delete<void>(`/api/advances/${id}`);
  }

  /**
   * Bulk delete advances
   *
   * @param ids - Array of advance IDs
   * @returns Delete operation result
   */
  async bulkDeleteAdvances(ids: string[]): Promise<ApiResult<void>> {
    return this.delete<void>('/api/advances/bulk', undefined, { ids });
  }

  /**
   * Approve or reject an advance
   *
   * @param id - Advance ID
   * @param payload - Approval data
   * @returns Updated advance result
   */
  async approveAdvance(id: string, payload: ApproveAdvanceRequest): Promise<ApiResult<Advance>> {
    return this.post<ApproveAdvanceRequest, Advance>(`/api/advances/${id}/approve`, payload);
  }

  /**
   * Export advances to Excel
   *
   * @param params - Query parameters for filtering
   * @returns Excel file blob
   */
  async exportExcel(params?: QueryRequest): Promise<ApiResult<Blob>> {
    return this.getDownload('/api/advances/export/excel', params);
  }
}

// ==================== EXPORT SINGLETON ====================

const advanceService = new AdvanceService();
export default advanceService;
