// ==============================|| HR API SERVICE ||============================== //

import BaseService from 'services/http/base-service';
import type { ApiResult, PaginationResult, QueryRequest } from 'services/http/types';

import type { Employee, EmployeeFormData } from '../types';

// ==================== REQUEST TYPES ====================

export interface CreateEmployeeRequest extends Omit<EmployeeFormData, 'code'> {
  // code will be auto-generated by server
}

export interface UpdateEmployeeRequest extends EmployeeFormData {}

// ==================== SERVICE CLASS ====================

/**
 * Employee Service Class
 * Extends BaseService to inherit all HTTP methods
 */
class EmployeeService extends BaseService {
  /**
   * Get paginated list of employees
   *
   * @param params - Query parameters (page, size, search, sort)
   * @returns Paginated result
   */
  async getEmployees(params?: QueryRequest): Promise<ApiResult<PaginationResult<Employee>>> {
    return this.get<PaginationResult<Employee>>('/api/hr/employees', params);
  }

  /**
   * Get a single employee by ID
   *
   * @param id - Employee ID
   * @returns Single employee result
   */
  async getEmployeeById(id: string): Promise<ApiResult<Employee>> {
    return this.get<Employee>(`/api/hr/employees/${id}`);
  }

  /**
   * Create a new employee
   *
   * @param payload - Employee data
   * @returns Created employee result
   */
  async createEmployee(payload: CreateEmployeeRequest): Promise<ApiResult<Employee>> {
    return this.post<CreateEmployeeRequest, Employee>('/api/hr/employees', payload);
  }

  /**
   * Update an existing employee
   *
   * @param id - Employee ID
   * @param payload - Updated data
   * @returns Updated employee result
   */
  async updateEmployee(id: string, payload: UpdateEmployeeRequest): Promise<ApiResult<Employee>> {
    return this.put<UpdateEmployeeRequest, Employee>(`/api/hr/employees/${id}`, payload);
  }

  /**
   * Delete an employee
   *
   * @param id - Employee ID
   * @returns Delete operation result
   */
  async deleteEmployee(id: string): Promise<ApiResult<void>> {
    return this.delete<void>(`/api/hr/employees/${id}`);
  }

  /**
   * Bulk delete employees
   *
   * @param ids - Array of employee IDs
   * @returns Delete operation result
   */
  async bulkDeleteEmployees(ids: string[]): Promise<ApiResult<void>> {
    return this.delete<void>('/api/hr/employees/bulk', undefined, { ids });
  }

  /**
   * Extend contract for an employee
   *
   * @param id - Employee ID
   * @param newExpiryDate - New expiry date
   * @returns Updated employee result
   */
  async extendContract(id: string, newExpiryDate: Date | string): Promise<ApiResult<Employee>> {
    return this.post<{ expiryDate: Date | string }, Employee>(`/api/hr/employees/${id}/extend-contract`, {
      expiryDate: newExpiryDate
    });
  }

  /**
   * Export employees to Excel
   *
   * @param params - Query parameters for filtering
   * @returns Excel file blob
   */
  async exportExcel(params?: QueryRequest): Promise<ApiResult<Blob>> {
    return this.getDownload('/api/hr/employees/export/excel', params);
  }
}

// ==================== EXPORT SINGLETON ====================

const employeeService = new EmployeeService();
export default employeeService;
