// ==============================|| STOCKTAKE API SERVICE ||============================== //

import { BaseService } from 'services/http';
import type { ApiResult, PaginationResult, QueryRequest } from 'services/http/types';

import type { Stocktake, StocktakeFormData } from '../types';

// ==================== REQUEST TYPES ====================

export interface CreateStocktakeRequest extends Omit<StocktakeFormData, 'code'> {
  // code will be auto-generated by server
}

export interface UpdateStocktakeRequest extends StocktakeFormData {}

// ==================== SERVICE CLASS ====================

/**
 * Stocktake Service Class
 * Extends BaseService to inherit all HTTP methods
 */
class StocktakeService extends BaseService {
  /**
   * Get paginated list of Stocktakes
   *
   * @param params - Query parameters (page, size, search, sort)
   * @returns Paginated result
   */
  async getStocktakes(params?: QueryRequest): Promise<ApiResult<PaginationResult<Stocktake>>> {
    return this.get<PaginationResult<Stocktake>>('/api/stocktakes', params);
  }

  /**
   * Get a single Stocktake by ID
   *
   * @param id - Stocktake ID
   * @returns Single Stocktake result
   */
  async getStocktakeById(id: string): Promise<ApiResult<Stocktake>> {
    return this.get<Stocktake>(`/api/stocktakes/${id}`);
  }

  /**
   * Create a new Stocktake
   *
   * @param payload - Stocktake data
   * @returns Created Stocktake result
   */
  async createStocktake(payload: CreateStocktakeRequest): Promise<ApiResult<Stocktake>> {
    return this.post<CreateStocktakeRequest, Stocktake>('/api/stocktakes', payload);
  }

  /**
   * Update an existing Stocktake
   *
   * @param id - Stocktake ID
   * @param payload - Updated data
   * @returns Updated Stocktake result
   */
  async updateStocktake(id: string, payload: UpdateStocktakeRequest): Promise<ApiResult<Stocktake>> {
    return this.put<UpdateStocktakeRequest, Stocktake>(`/api/stocktakes/${id}`, payload);
  }

  /**
   * Delete a Stocktake
   *
   * @param id - Stocktake ID
   * @returns Delete operation result
   */
  async deleteStocktake(id: string): Promise<ApiResult<void>> {
    return this.delete<void>(`/api/stocktakes/${id}`);
  }

  /**
   * Bulk delete Stocktakes
   *
   * @param ids - Array of Stocktake IDs
   * @returns Delete operation result
   */
  async bulkDeleteStocktakes(ids: string[]): Promise<ApiResult<void>> {
    return this.delete<void>('/api/stocktakes/bulk', undefined, { ids });
  }

  /**
   * Confirm stocktake (change status from draft to completed)
   *
   * @param id - Stocktake ID
   * @returns Updated Stocktake result
   */
  async confirmStocktake(id: string): Promise<ApiResult<Stocktake>> {
    return this.post<Record<string, never>, Stocktake>(`/api/stocktakes/${id}/confirm`, {});
  }

  /**
   * Export Stocktakes to Excel
   *
   * @param params - Query parameters for filtering
   * @returns Excel file blob
   */
  async exportExcel(params?: QueryRequest): Promise<ApiResult<Blob>> {
    return this.getDownload('/api/stocktakes/export/excel', params);
  }
}

// ==================== EXPORT SINGLETON ====================

const stocktakeService = new StocktakeService();
export default stocktakeService;
