// ==============================|| INVENTORY ISSUES API SERVICE ||============================== //

import { BaseService } from 'services/http';
import type { ApiResult, PaginationResult, QueryRequest } from 'services/http/types';

import type { InventoryIssue, InventoryIssueFormData } from '../types';

// ==================== REQUEST TYPES ====================

export interface CreateInventoryIssueRequest extends Omit<InventoryIssueFormData, 'code'> {
  // code will be auto-generated by server
}

export interface UpdateInventoryIssueRequest extends InventoryIssueFormData {}

// ==================== SERVICE CLASS ====================

/**
 * Inventory Issue Service Class
 * Extends BaseService to inherit all HTTP methods
 */
class InventoryIssueService extends BaseService {
  /**
   * Get paginated list of inventory issues
   *
   * @param params - Query parameters (page, size, search, sort)
   * @returns Paginated result
   */
  async getInventoryIssues(params?: QueryRequest): Promise<ApiResult<PaginationResult<InventoryIssue>>> {
    return this.get<PaginationResult<InventoryIssue>>('/api/inventory-issues', params);
  }

  /**
   * Get a single inventory issue by ID
   *
   * @param id - Inventory issue ID
   * @returns Single inventory issue result
   */
  async getInventoryIssueById(id: string): Promise<ApiResult<InventoryIssue>> {
    return this.get<InventoryIssue>(`/api/inventory-issues/${id}`);
  }

  /**
   * Create a new inventory issue
   *
   * @param payload - Inventory issue data
   * @returns Created inventory issue result
   */
  async createInventoryIssue(payload: CreateInventoryIssueRequest): Promise<ApiResult<InventoryIssue>> {
    return this.post<CreateInventoryIssueRequest, InventoryIssue>('/api/inventory-issues', payload);
  }

  /**
   * Update an existing inventory issue
   *
   * @param id - Inventory issue ID
   * @param payload - Updated data
   * @returns Updated inventory issue result
   */
  async updateInventoryIssue(id: string, payload: UpdateInventoryIssueRequest): Promise<ApiResult<InventoryIssue>> {
    return this.put<UpdateInventoryIssueRequest, InventoryIssue>(`/api/inventory-issues/${id}`, payload);
  }

  /**
   * Delete an inventory issue
   *
   * @param id - Inventory issue ID
   * @returns Delete operation result
   */
  async deleteInventoryIssue(id: string): Promise<ApiResult<void>> {
    return this.delete<void>(`/api/inventory-issues/${id}`);
  }

  /**
   * Bulk delete inventory issues
   *
   * @param ids - Array of inventory issue IDs
   * @returns Delete operation result
   */
  async bulkDeleteInventoryIssues(ids: string[]): Promise<ApiResult<void>> {
    return this.delete<void>('/api/inventory-issues/bulk', undefined, { ids });
  }

  /**
   * Confirm issue (change status from draft to issued)
   *
   * @param id - Inventory issue ID
   * @returns Updated inventory issue result
   */
  async confirmIssue(id: string): Promise<ApiResult<InventoryIssue>> {
    return this.post<Record<string, never>, InventoryIssue>(`/api/inventory-issues/${id}/confirm`, {});
  }

  /**
   * Export inventory issues to Excel
   *
   * @param params - Query parameters for filtering
   * @returns Excel file blob
   */
  async exportExcel(params?: QueryRequest): Promise<ApiResult<Blob>> {
    return this.getDownload('/api/inventory-issues/export/excel', params);
  }

  /**
   * Export inventory issues to PDF
   *
   * @param params - Query parameters for filtering
   * @returns PDF file blob
   */
  async exportPDF(params?: QueryRequest): Promise<ApiResult<Blob>> {
    return this.getDownload('/api/inventory-issues/export/pdf', params);
  }
}

// ==================== EXPORT SINGLETON ====================

const inventoryIssueService = new InventoryIssueService();
export default inventoryIssueService;
