// ==============================|| PAB CREATE PAGE ||============================== //

import CloseOutlined from '@ant-design/icons/CloseOutlined';
import SaveOutlined from '@ant-design/icons/SaveOutlined';
import SendOutlined from '@ant-design/icons/SendOutlined';
import { Stack, Button } from '@mui/material';
import Grid from '@mui/material/Grid';
import { Formik, Form } from 'formik';
import { useCallback } from 'react';
import { useNavigate } from 'react-router-dom';

// project imports
import MainCard from 'components/MainCard';

import PabForm from '../components/PabForm';
import { PAB_URLS } from '../types/constants';
import type { PabFormData } from '../types/index';
import { pabSchema, pabDefaultValues } from '../validation';

// ==============================|| PAB CREATE PAGE ||============================== //

const PabCreatePage = () => {
  const navigate = useNavigate();

  // Initial form values
  const initialValues: PabFormData = {
    ...pabDefaultValues,
    code: 'PAB-XXXX' // Placeholder - will be generated by server
  };

  // Handle form submission
  const handleSubmit = useCallback(
    async (values: PabFormData) => {
      // TODO: Call API to create PAB
      console.warn('Creating PAB:', values);
      await new Promise((resolve) => setTimeout(resolve, 1000));

      // Mock: Generate a new ID and navigate to detail page
      const mockNewId = `mock-${Date.now()}`;
      alert('Tạo PAB thành công! (Mock)');
      navigate(PAB_URLS.DETAIL(mockNewId));
    },
    [navigate]
  );

  // Handle submit for approval
  const handleSubmitForApproval = useCallback(
    async (values: PabFormData) => {
      // TODO: Call API to submit PAB for approval
      console.warn('Submitting PAB for approval:', values);
      await new Promise((resolve) => setTimeout(resolve, 1000));

      // Mock: Generate a new ID and navigate to detail page
      const mockNewId = `mock-${Date.now()}`;
      alert('Gửi phê duyệt thành công! (Mock)');
      navigate(PAB_URLS.DETAIL(mockNewId));
    },
    [navigate]
  );

  // Handle cancel
  const handleCancel = useCallback(() => {
    navigate(PAB_URLS.LIST);
  }, [navigate]);

  return (
    <Formik initialValues={initialValues} validationSchema={pabSchema} onSubmit={handleSubmit} validateOnChange validateOnBlur>
      {({ isSubmitting, dirty, values }) => (
        <Form>
          <MainCard
            title="Lập phương án kinh doanh"
            secondary={
              <Stack direction="row" spacing={1}>
                <Button variant="outlined" color="secondary" startIcon={<CloseOutlined />} onClick={handleCancel} disabled={isSubmitting}>
                  Quay lại
                </Button>
                <Button variant="outlined" color="secondary" onClick={handleCancel} disabled={isSubmitting}>
                  Hủy
                </Button>
                {values.status === 'draft' && (
                  <Button
                    variant="contained"
                    color="primary"
                    startIcon={<SendOutlined />}
                    onClick={() => handleSubmitForApproval(values)}
                    disabled={isSubmitting || !dirty}
                  >
                    {isSubmitting ? 'Đang gửi...' : 'Gửi phê duyệt'}
                  </Button>
                )}
                <Button type="submit" variant="contained" color="primary" startIcon={<SaveOutlined />} disabled={isSubmitting || !dirty}>
                  {isSubmitting ? 'Đang lưu...' : 'Lưu PAB'}
                </Button>
              </Stack>
            }
          >
            <Grid container spacing={3} sx={{ p: 1 }}>
              <Grid size={12}>
                <PabForm mode="create" />
              </Grid>
            </Grid>
          </MainCard>
        </Form>
      )}
    </Formik>
  );
};

export default PabCreatePage;
