import { SaveOutlined, CloseOutlined } from '@ant-design/icons';
import { Stack, Button } from '@mui/material';
import Grid from '@mui/material/Grid';
import { Formik, Form } from 'formik';
import { useCallback } from 'react';
import { useNavigate } from 'react-router-dom';

// project imports
import MainCard from 'components/MainCard';

import ShipmentForm from '../components/ShipmentForm';
import { SHIPMENT_URLS } from '../types/constants';
import type { ShipmentFormData } from '../types/index';
import { shipmentSchema, shipmentDefaultValues } from '../validation';

// ==============================|| SHIPMENT CREATE PAGE ||============================== //

const ShipmentCreatePage = () => {
  const navigate = useNavigate();

  // Initial form values
  const initialValues: ShipmentFormData = {
    ...shipmentDefaultValues,
    code: 'PX-XXXX' // Placeholder - will be generated by server
  };

  // Handle form submission
  const handleSubmit = useCallback(
    async (values: ShipmentFormData) => {
      // TODO: Call API to create shipment
      console.warn('Creating shipment:', values);
      await new Promise((resolve) => setTimeout(resolve, 1000));

      // Mock: Generate a new ID and navigate to detail page
      const mockNewId = `mock-${Date.now()}`;
      alert('Tạo phiếu xuất thành công! (Mock)');
      navigate(SHIPMENT_URLS.DETAIL(mockNewId));
    },
    [navigate]
  );

  // Handle cancel
  const handleCancel = useCallback(() => {
    navigate(SHIPMENT_URLS.LIST);
  }, [navigate]);

  return (
    <Formik initialValues={initialValues} validationSchema={shipmentSchema} onSubmit={handleSubmit} validateOnChange validateOnBlur>
      {({ isSubmitting, dirty, values }) => (
        <Form>
          <MainCard
            title="Tạo phiếu xuất mới"
            secondary={
              <Stack direction="row" spacing={1}>
                <Button variant="outlined" color="secondary" startIcon={<CloseOutlined />} onClick={handleCancel} disabled={isSubmitting}>
                  Quay lại danh sách
                </Button>
                <Button type="submit" variant="contained" color="primary" startIcon={<SaveOutlined />} disabled={isSubmitting || !dirty}>
                  {isSubmitting ? 'Đang lưu...' : 'Lưu'}
                </Button>
              </Stack>
            }
          >
            <Grid container spacing={3} sx={{ p: 1 }}>
              <Grid size={12}>
                <ShipmentForm mode="create" />
              </Grid>
            </Grid>
          </MainCard>
        </Form>
      )}
    </Formik>
  );
};

export default ShipmentCreatePage;
