// ==============================|| SKU API SERVICE ||============================== //

import { BaseService } from 'services/http';
import type { ApiResult, PaginationResult, QueryRequest } from 'services/http/types';

import type { Sku, SkuFormData } from '../types';

// ==================== REQUEST TYPES ====================

export interface CreateSkuRequest extends Omit<SkuFormData, 'code' | 'name' | 'systemQuantity' | 'reservedQuantity' | 'availableQuantity'> {
  // code, name, quantities will be auto-generated by server
}

export interface UpdateSkuRequest extends SkuFormData {}

// ==================== SERVICE CLASS ====================

/**
 * SKU Service Class
 * Extends BaseService to inherit all HTTP methods
 */
class SkuService extends BaseService {
  /**
   * Get paginated list of SKUs
   *
   * @param params - Query parameters (page, size, search, sort)
   * @returns Paginated result
   */
  async getSkus(params?: QueryRequest): Promise<ApiResult<PaginationResult<Sku>>> {
    return this.get<PaginationResult<Sku>>('/api/skus', params);
  }

  /**
   * Get a single SKU by ID
   *
   * @param id - SKU ID
   * @returns Single SKU result
   */
  async getSkuById(id: string): Promise<ApiResult<Sku>> {
    return this.get<Sku>(`/api/skus/${id}`);
  }

  /**
   * Create a new SKU
   *
   * @param payload - SKU data
   * @returns Created SKU result
   */
  async createSku(payload: CreateSkuRequest): Promise<ApiResult<Sku>> {
    return this.post<CreateSkuRequest, Sku>('/api/skus', payload);
  }

  /**
   * Update an existing SKU
   *
   * @param id - SKU ID
   * @param payload - Updated data
   * @returns Updated SKU result
   */
  async updateSku(id: string, payload: UpdateSkuRequest): Promise<ApiResult<Sku>> {
    return this.put<UpdateSkuRequest, Sku>(`/api/skus/${id}`, payload);
  }

  /**
   * Delete a SKU
   *
   * @param id - SKU ID
   * @returns Delete operation result
   */
  async deleteSku(id: string): Promise<ApiResult<void>> {
    return this.delete<void>(`/api/skus/${id}`);
  }

  /**
   * Bulk delete SKUs
   *
   * @param ids - Array of SKU IDs
   * @returns Delete operation result
   */
  async bulkDeleteSkus(ids: string[]): Promise<ApiResult<void>> {
    return this.delete<void>('/api/skus/bulk', undefined, { ids });
  }

  /**
   * Export SKUs to Excel
   *
   * @param params - Query parameters for filtering
   * @returns Excel file blob
   */
  async exportExcel(params?: QueryRequest): Promise<ApiResult<Blob>> {
    return this.getDownload('/api/skus/export/excel', params);
  }
}

// ==================== EXPORT SINGLETON ====================

const skuService = new SkuService();
export default skuService;
