import { SaveOutlined, CloseOutlined } from '@ant-design/icons';
import { Stack, Button } from '@mui/material';
import Grid from '@mui/material/Grid';
import { Formik, Form } from 'formik';
import { useCallback } from 'react';
import { useNavigate } from 'react-router-dom';

// project imports
import MainCard from 'components/MainCard';

import DispatchOrderForm from '../components/DispatchOrderForm';
import type { DispatchOrderFormData } from '../types';
import { DISPATCH_ORDER_URLS } from '../types/constants';
import { dispatchOrderSchema, dispatchOrderDefaultValues } from '../validation';

// ==============================|| DISPATCH ORDER CREATE PAGE ||============================== //

const DispatchOrderCreatePage = () => {
  const navigate = useNavigate();

  // Initial form values
  const initialValues: DispatchOrderFormData = {
    ...dispatchOrderDefaultValues,
    orderCode: 'DO-XXXX' // Placeholder - will be generated by server
  };

  // Handle form submission (mock)
  const handleSubmit = useCallback(
    async (values: DispatchOrderFormData) => {
      // Mock API call - simulate network delay
      console.warn('Creating dispatch order:', values);
      await new Promise((resolve) => setTimeout(resolve, 1000));

      // Mock: Generate a new ID and navigate to detail page
      const mockNewId = `mock-${Date.now()}`;
      alert('Tạo lệnh điều động thành công! (Mock)');
      navigate(DISPATCH_ORDER_URLS.DETAIL(mockNewId));
    },
    [navigate]
  );

  // Handle cancel
  const handleCancel = useCallback(() => {
    navigate(DISPATCH_ORDER_URLS.LIST);
  }, [navigate]);

  return (
    <Formik initialValues={initialValues} validationSchema={dispatchOrderSchema} onSubmit={handleSubmit} validateOnChange validateOnBlur>
      {({ isSubmitting, dirty }) => (
        <Form>
          <MainCard
            title="Tạo lệnh điều động mới"
            secondary={
              <Stack direction="row" spacing={1}>
                <Button variant="outlined" color="secondary" startIcon={<CloseOutlined />} onClick={handleCancel} disabled={isSubmitting}>
                  Quay lại danh sách
                </Button>
                <Button type="submit" variant="contained" color="primary" startIcon={<SaveOutlined />} disabled={isSubmitting || !dirty}>
                  {isSubmitting ? 'Đang lưu...' : 'Lưu'}
                </Button>
              </Stack>
            }
          >
            <Grid container spacing={3} sx={{ p: 1 }}>
              <Grid size={12}>
                <DispatchOrderForm mode="create" />
              </Grid>
            </Grid>
          </MainCard>
        </Form>
      )}
    </Formik>
  );
};

export default DispatchOrderCreatePage;
